server:
  port: 8080

spring:
  main:
    web-application-type: servlet

# src/main/resources/application.yml
postmark:
  server-token: ${POSTMARK_SERVER_TOKEN:}
  template:
    reset-password-id: ${POSTMARK_RESET_PASSWORD_TEMPLATE_ID:0}
    signup-id: ${POSTMARK_SIGNUP_TEMPLATE_ID:0}

app:
  mail:
    from: ${APP_MAIL_FROM:noreply@example.com}


# values for the email templates
  product-name: ${APP_PRODUCT_NAME:SnapLink}
  login-url: ${APP_LOGIN_URL:http://localhost:5173/login}
  support-email: ${APP_SUPPORT_EMAIL:support@example.com}
  live-chat-url: ${APP_LIVE_CHAT_URL:https://example.com/live-chat}
  sender-name: ${APP_SENDER_NAME:SnapLink Support}
  help-url: ${APP_HELP_URL:https://example.com/help}
  support-url: ${APP_SUPPORT_URL:https://example.com/support}

  security:
    reset-token-expiration-hours: ${APP_RESET_TOKEN_EXPIRATION_HOURS:1}
  trial:
    length-days: ${APP_TRIAL_LENGTH_DAYS:14}
